MACCS_DESCRIPTIONS = {
    0: "Wildcard (unused)",
    1: "Isotope present",
    2: "Atom number > 103",
    3: "Group IVA, VA, VIA metals (Ge, Sn, Pb, As, Sb, Bi, Se, Te, Po)",
    4: "Actinide element",
    5: "Group IIIB, IVB metal (Sc, Ti, Y, Zr, Hf)",
    6: "Lanthanide element",
    7: "Group VB, VIB, VIIB metal (V, Cr, Mn, Nb, Mo, Tc, Ta, W, Re)",
    8: "Quaternary carbon (4 heavy atom neighbors)",
    9: "Group VIII metal (Fe, Co, Ni, Ru, Rh, Pd, Os, Ir, Pt)",
    10: "Group IIA alkaline earth (Be, Mg, Ca, Sr, Ba, Ra)",
    11: "4-membered ring",
    12: "Group IB, IIB metal (Cu, Zn, Ag, Cd, Au, Hg)",
    13: "On or S on aromatic ring",
    14: "Nitrogen-oxygen single bond (N-O)",
    15: "More than one non-carbon heavy atom adjacent to each other (hetero-hetero)",
    16: "Presence of sulfur",
    17: "1,3-dioxolane ring (O-C-O in 5-membered ring)",
    18: "Ring with 7+ atoms",
    19: "Presence of nitrogen",
    20: "Presence of oxygen",
    21: "Heterocyclic atom in ring",
    22: "Quaternary carbon or nitrogen (4 neighbors)",
    23: "Phosphorus present",
    24: "Sulfur-nitrogen bond (S-N)",
    25: "Triple bond present",
    26: "Sulfur-oxygen bond (S-O)",
    27: "Nitrogen-carbon-nitrogen fragment (N-C-N)",
    28: "Carbon-oxygen-carbon fragment (C-O-C)",
    29: "Sulfur-sulfur bond (S-S)",
    30: "Carbon-carbon-nitrogen fragment (C-C=N)",
    31: "3-membered ring (epoxide, aziridine, etc.)",
    32: "Group IA alkali metal (Li, Na, K, Rb, Cs, Fr)",
    33: "Nitrogen-carbon-carbon-nitrogen fragment",
    34: "Nitrogen on 5-membered heterocyclic ring",
    35: "Oxygen on 5-membered heterocyclic ring",
    36: "Nitrogen on 6-membered heterocyclic ring",
    37: "Oxygen on 6-membered heterocyclic ring",
    38: "Sulfur on 5-membered heterocyclic ring",
    39: "Sulfur on 6-membered heterocyclic ring",
    40: "Any heteroatom in 5-membered ring not adjacent to another heteroatom",
    41: "Any heteroatom in 5-membered ring adjacent to another heteroatom",
    42: "Any heteroatom in 6-membered ring not adjacent to another heteroatom",
    43: "Any heteroatom in 6-membered ring adjacent to another heteroatom",
    44: "Carbon-halogen bond on non-aromatic atom",
    45: "Nitrogen-carbon-carbon-oxygen fragment",
    46: "Halogen present",
    47: "Nitrogen-nitrogen-carbon fragment (N-N-C)",
    48: "Carbon-nitrogen-carbon fragment (C=N-C)",
    49: "Nitrogen-oxygen-carbon fragment",
    50: "Oxygen-carbon-oxygen fragment",
    51: "Positively charged atom",
    52: "Negatively charged atom",
    53: "Carbon-nitrogen-carbon(=O) fragment (urea/amide-like)",
    54: "Carbon-sulfur-carbon fragment",
    55: "Nitrogen-carbon-nitrogen(=O) fragment",
    56: "Nitrogen-sulfur fragment",
    57: "Carbon(=O)-oxygen-carbon fragment (ester)",
    58: "Nitrogen-phosphorus fragment",
    59: "Carbon-selenium fragment",
    60: "Silicon present",
    61: "Carbon#nitrogen (nitrile)",
    62: "Carbon-carbon(=C)-carbon fragment (allyl)",
    63: "Nitrogen-oxygen-hydrogen fragment (hydroxylamine)",
    64: "Oxygen-oxygen fragment (peroxide)",
    65: "Fluorine-carbon-fluorine fragment (geminal difluoride)",
    66: "Sulfur=carbon fragment (thioketone)",
    67: "Nitrogen-hydrogen (secondary or primary amine)",
    68: "Carbon-oxygen-hydrogen fragment (hydroxyl on non-aromatic carbon)",
    69: "Oxygen-carbon-carbon-nitrogen fragment",
    70: "Nitrogen-nitrogen fragment",
    71: "Non-aromatic ring containing nitrogen",
    72: "Carbon-oxygen-carbon=oxygen fragment (ester/acid anhydride)",
    73: "Carbon(=O)-OH fragment (carboxylic acid)",
    74: "Carbon-sulfur-hydrogen fragment (thiol)",
    75: "Carbon-carbon=carbon fragment (non-aromatic double bond)",
    76: "Silicon-oxygen fragment",
    77: "Carbon-oxygen-nitrogen fragment",
    78: "Nitrogen-carbon=oxygen fragment (amide)",
    79: "Nitrogen in 3-membered ring (aziridine)",
    80: "Carbon-nitrogen-nitrogen=carbon fragment",
    81: "Aromatic nitrogen",
    82: "5-membered aromatic heterocyclic ring",
    83: "3-membered ring",
    84: "Nitrogen-carbon-nitrogen-carbon fragment",
    85: "Sulfur in ring",
    86: "Oxygen-carbon-nitrogen-carbon fragment",
    87: "Nitrogen-carbon-oxygen-carbon fragment",
    88: "Carbon in ring with exocyclic double bond to non-carbon",
    89: "Carbon-sulfur-carbon-carbon fragment",
    90: "Carbon-oxygen-carbon-carbon fragment",
    91: "Nitrogen=carbon-nitrogen-carbon fragment",
    92: "Carbon-carbon(=O)-carbon-carbon fragment",
    93: "Carbon-nitrogen-carbon-nitrogen fragment",
    94: "Carbon-oxygen-carbon-oxygen fragment",
    95: "Nitrogen-nitrogen-carbon-nitrogen fragment",
    96: "Oxygen=carbon-nitrogen-nitrogen fragment",
    97: "Nitrogen-carbon-nitrogen-nitrogen fragment",
    98: "Carbon-oxygen-carbon-nitrogen fragment",
    99: "Carbon in 2 different fused rings",
    100: "Carbon in 3+ fused rings",
    101: "Quaternary nitrogen (positive)",
    102: "Aromatic ring with nitrogen and oxygen",
    103: "Non-aromatic ring with nitrogen",
    104: "Carbon-carbon(=O)-nitrogen-carbon fragment (amide bond)",
    105: "3 or more fused rings",
    106: "Non-aromatic nitrogen with two carbon neighbors",
    107: "Aromatic ring with only carbon and hydrogen",
    108: "Aromatic nitrogen in 6-membered ring (pyridine-like)",
    109: "Carbon=carbon-nitrogen fragment (enamine/imine)",
    110: "Sulfur-aromatic ring bond",
    111: "Nitrogen-carbon(=O)-carbon fragment",
    112: "Oxygen-aromatic ring bond",
    113: "Non-aromatic ring containing oxygen",
    114: "Carbon-carbon(=O)-oxygen-carbon fragment (ester in chain)",
    115: "Aromatic ring with nitrogen",
    116: "3-membered heterocyclic ring",
    117: "Isolated aromatic ring (no fused rings)",
    118: "Nitrogen connected to 2 aromatic rings",
    119: "Non-aromatic ring with exocyclic double bond",
    120: "Carbon-carbon(=C)-carbon-carbon fragment (conjugated)",
    121: "Ring with 8+ atoms",
    122: "4-membered heterocyclic ring",
    123: "Aromatic ring connected to non-aromatic ring",
    124: "6-membered non-aromatic ring with one nitrogen",
    125: "Aromatic ring",
    126: "Non-aromatic ring with 6+ atoms",
    127: "Non-aromatic carbon-carbon double bond",
    128: "Two aromatic rings connected by single bond (biaryl)",
    129: "5-membered non-aromatic ring",
    130: "Nitrogen in non-aromatic ring with adjacent carbonyl",
    131: "Two fused aromatic rings (naphthalene-like)",
    132: "Aromatic ring with substituent",
    133: "5-membered aromatic ring",
    134: "Nitrogen-carbon(=O)-nitrogen fragment (urea)",
    135: "Aromatic ring with nitrogen and sulfur",
    136: "6-membered non-aromatic ring with one oxygen",
    137: "Aromatic ring with halogen substituent",
    138: "Aromatic ring with hydroxyl substituent",
    139: "5-membered non-aromatic ring with nitrogen",
    140: "Two connected non-aromatic rings",
    141: "6-membered aromatic ring",
    142: "Carbon-carbon=carbon-carbon fragment (diene/conjugated)",
    143: "Carbon=carbon in ring",
    144: "Carbon-nitrogen=carbon fragment",
    145: "Spiro ring system",
    146: "5-membered non-aromatic ring with oxygen",
    147: "Bridged ring system",
    148: "Non-aromatic ring with multiple heteroatoms",
    149: "Aromatic ring with amino substituent",
    150: "Non-aromatic ring containing sulfur",
    151: "Aromatic ring with two+ non-carbon substituents",
    152: "Two fused non-aromatic rings",
    153: "Oxygen in two different rings",
    154: "Nitrogen in two different rings",
    155: "Carbon=oxygen fragment (carbonyl)",
    156: "Aromatic ring with methyl substituent",
    157: "Carbon-nitrogen bond",
    158: "Carbon-oxygen bond",
    159: "Carbon-sulfur bond",
    160: "Any ring",
    161: "Carbon-carbon bond",
    162: "Nitrogen with hydrogen",
    163: "Oxygen with hydrogen (hydroxyl/carboxylic OH)",
    164: "3 or more different element types",
    165: "Molecule has 2+ fragments",
}
